/** Service Clarity: a simple, human survey places one clear customer decision at the center of each step. */
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { useParams } from "react-router-dom";
import { Check, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Clock3, LockKeyhole, MessageCircleHeart } from "lucide-react";
import { toast } from "sonner";
import { BrandMark } from "@/components/BrandMark";
import { useAppData } from "@/contexts/AppDataContext";
import { getSurveyContextByToken } from "@/services/invitationsService";
import { submitSurveyResponse } from "@/services/responsesService";
import { SURVEY_QUESTIONS } from "@/types/sis";

type SurveyMode = "form" | "thanks";

function SurveyFrame({ children }: { children: ReactNode }) { return <div className="survey-page"><main><header className="survey-header"><BrandMark /><span>Encuesta confidencial</span></header>{children}<footer>SIS Insight · Experiencia del Cliente · Corporación SIS</footer></main></div>; }

function StatusScreen({ type }: { type: "invalid" | "expired" | "completed" | "unavailable" }) {
  const config = { invalid: { icon: CircleAlert, title: "Este enlace no es válido", copy: "Compruebe que la dirección sea correcta o solicite un nuevo enlace a su contacto de Corporación SIS." }, expired: { icon: Clock3, title: "Esta encuesta ha vencido", copy: "El periodo para responder esta evaluación ya finalizó. Gracias por su disposición a participar." }, completed: { icon: CheckCircle2, title: "Esta evaluación ya fue completada", copy: "Agradecemos su participación y el tiempo que dedicó a compartir su opinión con Corporación SIS." }, unavailable: { icon: LockKeyhole, title: "Esta encuesta no está disponible", copy: "La evaluación asociada no se encuentra activa. Comuníquese con su contacto de Corporación SIS si necesita apoyo." } }[type]; const Icon = config.icon; return <SurveyFrame><section className="survey-card status-screen"><div><p className="status-kicker">Estado de evaluación</p><div className="status-icon"><Icon size={29} /></div><h1>{config.title}</h1><p>{config.copy}</p></div></section></SurveyFrame>;
}

function RatingScale({ value, onChange, questionIndex }: { value: number | null; onChange: (rating: number) => void; questionIndex: number }) { const labels = ["Muy insatisfecho", "Insatisfecho", "Regular", "Muy satisfecho", "Excelente"]; return <div className="rating-scale" role="radiogroup" aria-label={`Calificación de la pregunta ${questionIndex + 1}`}>{[1, 2, 3, 4, 5].map((rating) => <button key={rating} role="radio" type="button" aria-checked={value === rating} onClick={() => onChange(rating)} className={value === rating ? "rating-choice chosen" : "rating-choice"}><strong>{rating}</strong><span>{labels[rating - 1]}</span></button>)}</div>; }

export default function PublicSurveyPage() {
  const { token = "" } = useParams(); const { isReady } = useAppData(); const context = useMemo(() => isReady ? getSurveyContextByToken(token) : undefined, [isReady, token]);
  const [answers, setAnswers] = useState<(number | null)[]>([null, null, null, null, null]); const [comment, setComment] = useState(""); const [contactRequested, setContactRequested] = useState<boolean | undefined>(); const [step, setStep] = useState(0); const [mode, setMode] = useState<SurveyMode>("form"); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { setAnswers([null, null, null, null, null]); setComment(""); setContactRequested(undefined); setStep(0); setMode("form"); }, [token]);
  if (!isReady) return <SurveyFrame><section className="survey-card loading-survey">Cargando encuesta…</section></SurveyFrame>;
  if (!context) return <StatusScreen type="invalid" />; if (context.invitation.status === "expired") return <StatusScreen type="expired" />; if (context.invitation.status === "completed") return <StatusScreen type="completed" />; if (context.campaign.status !== "active" || context.invitation.status !== "pending") return <StatusScreen type="unavailable" />;
  if (mode === "thanks") return <SurveyFrame><section className="survey-card thanks-screen"><div className="thanks-mark"><CheckCircle2 size={32} /></div><p className="kicker">Respuesta enviada</p><h1>Gracias por compartir su experiencia.</h1><p>Su opinión será considerada dentro de los procesos de mejora continua de Corporación SIS.</p></section></SurveyFrame>;
  const closing = step === 5; const progress = closing ? 100 : ((step + 1) / 6) * 100; const proceed = () => { if (!answers[step]) { toast.error("Seleccione una calificación para continuar."); return; } setStep((current) => Math.min(current + 1, 5)); }; const submit = (event: FormEvent) => { event.preventDefault(); if (answers.some((answer) => !answer)) { toast.error("Complete las cinco calificaciones antes de enviar."); return; } setSubmitting(true); window.setTimeout(() => { try { submitSurveyResponse({ token, answers: answers as [number, number, number, number, number], comment, contactRequested }); setMode("thanks"); } catch (error) { toast.error(error instanceof Error ? error.message : "No fue posible enviar la encuesta."); } finally { setSubmitting(false); } }, 450); };
  return <SurveyFrame><section className="survey-card"><header className="survey-intro"><p className="kicker">Evaluación de servicio</p><h1>{closing ? "Un último detalle" : "¿Cómo ha sido su experiencia?"}</h1><p>{closing ? "Si lo desea, comparta más contexto para ayudarnos a mejorar." : "Sus respuestas nos ayudan a cuidar la calidad del servicio que recibe."}</p><div className="survey-context"><span><b>Cliente</b>{context.client.commercialName}</span><span><b>Servicio</b>{context.campaign.serviceType}</span><span><b>Periodo</b>{context.campaign.period}</span></div></header><form onSubmit={submit} className="survey-form"><div className="survey-progress"><div><span>Pregunta {closing ? "5" : step + 1} de 5</span><span>{closing ? "Finalizar" : `${step + 1} de 5`}</span></div><i><em style={{ width: `${progress}%` }} /></i></div>{!closing ? <div className="question-panel" key={step}><p className="question-number">Pregunta {String(step + 1).padStart(2, "0")}</p><h2>{SURVEY_QUESTIONS[step]}</h2><RatingScale questionIndex={step} value={answers[step]} onChange={(rating) => setAnswers((current) => current.map((answer, index) => index === step ? rating : answer))} /></div> : <div className="question-panel close-panel"><div className="question-icon"><MessageCircleHeart size={22} /></div><h2>¿Desea informarnos alguna situación, observación o aspecto que debamos mejorar?</h2><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={1000} rows={5} placeholder="Escriba aquí su comentario (opcional)" /><p className="character-count">{comment.length} / 1000</p><fieldset><legend>¿Desea que un representante de Corporación SIS se comunique con usted?</legend><div><button className={contactRequested === true ? "contact-choice selected" : "contact-choice"} type="button" onClick={() => setContactRequested(true)}><Check size={15} />Sí, deseo seguimiento</button><button className={contactRequested === false ? "contact-choice selected" : "contact-choice"} type="button" onClick={() => setContactRequested(false)}>No, por ahora</button></div></fieldset></div>}<div className="survey-actions"><button type="button" onClick={() => setStep((current) => Math.max(0, current - 1))} className={step === 0 ? "back-button hidden" : "back-button"}><ChevronLeft size={17} />Anterior</button>{closing ? <button className="action-button survey-submit" disabled={submitting} type="submit">{submitting ? "Enviando…" : "Enviar evaluación"}<ChevronRight size={17} /></button> : <button type="button" className="action-button survey-submit" onClick={proceed}>Continuar<ChevronRight size={17} /></button>}</div></form></section></SurveyFrame>;
}
